apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: test
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
      nodePort: 31022
  type: NodePort

