apiVersion: v1
kind: ServiceAccount
metadata:
  name: mosquitto
  # Change if you want to deploy to somewhere other then default
  namespace: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  # Change if you want to deploy to somewhere other then default
  namespace: test
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      serviceAccountName: mosquitto
      containers:
        - image: lansible/mosquitto:2.0.5
          imagePullPolicy: IfNotPresent
          name: mosquitto
          securityContext:
            capabilities:
                drop:
                  - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          readinessProbe:
            tcpSocket:
              port: mqtt
            timeoutSeconds: 5
          ports:
            - containerPort: 1883
              name: mqtt
          volumeMounts:
            - name: mosquitto-config
              mountPath: /config
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config

